const xppVisitor = require("./lib/xppVisitor").xppVisitor;

/**
 * This Visitor walks the tree generated by parsers and produces code
 *
 * @returns {object}
 */
class Visitor extends xppVisitor {
  /**
   * Entry point of tree visiting
   *
   * @param {object} ctx
   * @returns {string}
   */
  start(ctx) {
    return this.visitProgram(ctx);
  }

  visitChildren(ctx) {
    let code = "";

    for (let i = 0; i < ctx.getChildCount(); i++) {
      code += this.visit(ctx.getChild(i));
    }

    return code.trim();
  }

  visitTerminal(ctx) {
    return ctx.getText();
  }
}

module.exports = Visitor;
